app/catalog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, patterns
from django.views.generic import TemplateView
from django.views.decorators.csrf import csrf_exempt

from .views import ItemView, RentView, SaleView, OrderView, PrintItemView, ObjectsByRegionView, \
    SaleByTypeView, RentByTypeView, SaleByRegionView, RentByRegionView, \
    SaleByCityView, RentByCityView, ObjectsByTypeView, ObjectsByCityView, \
    SearchView, RegionView, CityView, SpecialRentView, SpecialSaleView, IndexView, \
    PostObjectView, ProcessImage4PostObject, PostObjectImagesView, XMLExportView

urlpatterns = patterns('',
    #Главная
    url(r'^$', IndexView.as_view(), name='catalog-index'),

    # блок добавления объектов
    url(r'^post-object/$', PostObjectView.as_view(), name='catalog-post-object'),
    url(r'^post-object-images/$', PostObjectImagesView.as_view(), name='catalog-post-object-images'),
    url(r'^process-image-post-object/$', csrf_exempt(ProcessImage4PostObject.as_view()), name='catalog-post-object-process-image'),

    #поиск
    url(r'^search/$', SearchView.as_view(), name='catalog-search'),

    #заказ
    url(r'^order/$', OrderView.as_view(), name='catalog-order'),
    url(r'^order-success/$', TemplateView.as_view(template_name='catalog/order/order-success.html'),
        name='catalog-order-success'),

    #Города и районы
    url(r'^city/(?P<slug>[\w-]+)/$', CityView.as_view(), name='catalog-city'),
    url(r'^region/(?P<slug>[\w-]+)/$', RegionView.as_view(), name='catalog-region'),

    #######Продажа######
    #Продажа
    url(r'^sale/$', SaleView.as_view(), name='catalog-sale'),
    url(r'^special-sale/$', SpecialSaleView.as_view(), name='catalog-special-sale'),

    #Продажа по типам недвижки
    url(r'^sale-by-type/(?P<slug>[\w-]+)/$', SaleByTypeView.as_view(), name='catalog-sale-by-type'),

    #Продажа по городам
    url(r'^sale-by-region/(?P<slug>[\w-]+)/$', SaleByRegionView.as_view(), name='catalog-sale-by-region'),

    #Продажа по муниципалитетам
    url(r'^sale-by-city/(?P<slug>[\w-]+)/$', SaleByCityView.as_view(), name='catalog-sale-by-city'),


    ######все объекты######
    # #объекты по регионам
    url(r'^objects-by-region/(?P<slug>[\w-]+)/$', ObjectsByRegionView.as_view(), name='catalog-objects-by-region'),

    #объекты по городам
    url(r'^objects-by-city/(?P<slug>[\w-]+)/$', ObjectsByCityView.as_view(), name='catalog-objects-by-city'),

    #объекты по типам недвижки
    url(r'^objects-by-type/(?P<slug>[\w-]+)/$', ObjectsByTypeView.as_view(), name='catalog-objects-by-type'),


    #######Аренда#######
    #Аренда
    url(r'^rent/$', RentView.as_view(), name='catalog-rent'),
    url(r'^special-rent/$', SpecialRentView.as_view(), name='catalog-special-rent'),

    #Аренда по типам недвижки
    url(r'^rent-by-type/(?P<slug>[\w-]+)/$', RentByTypeView.as_view(), name='catalog-rent-by-type'),

    #Аренда по региону
    url(r'^rent-by-region/(?P<slug>[\w-]+)/$', RentByRegionView.as_view(), name='catalog-rent-by-region'),

    #Аренда по муниципалитетам
    url(r'^rent-by-city/(?P<slug>[\w-]+)/$', RentByCityView.as_view(), name='catalog-rent-by-city'),


    #######Прочее######
    #объект на печать
    url(r'^print/(?P<slug>[\w-]+)/$', PrintItemView.as_view(), name='catalog-item-print'),
    #страница объекта
    url(r'^(?P<slug>[\w-]+)/$', ItemView.as_view(), name='catalog-item'),

    #Экспорт в XML
    url(r'^xml-export\.xml$', XMLExportView.as_view(), name='catalog-xml'),
)

bravo/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

from filebrowser.sites import site

admin.autodiscover()

urlpatterns = patterns('',
    (r'^tinymce/', include('tinymce.urls')),

    url(r'^ajaximage/', include('ajaximage.urls')),

    url(r'^admin/filebrowser/', include(site.urls)),

    (r'^grappelli/', include('grappelli.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^captcha/', include('captcha.urls')),
)

urlpatterns += i18n_patterns('',

    url(r'^response/', include('app.response.urls')),

    url(r'^contacts/', include('app.contacts.urls')),

    url(r'^article/', include('app.article.urls')),

    url(r'^news/', include('app.news.urls')),

    url(r'^catalog/', include('app.catalog.urls')),

    url(r'^capture/', include('app.capture.urls')),

    # XDP-page
    url(r'', include('xendor.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            }),
    )


if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

app/catalog/models.py
# -*- coding: utf-8 -*-
import datetime

from django.db import models
from django.db.models import Count
from django.utils.translation import ugettext_lazy as _

from tinymce.models import HTMLField
from ajaximage.fields import AjaxImageField

from xendor.models import Page
from xendor.utils import generate_slug
from xendor.utils import getmd5


#todo: похерить вместе с миграциями
#бутор для совместимости с джанговскими миграциями
def upload_city(instance, filename):
    pass


def upload_item(instance, filename):
    pass


def upload_city_image(instance, filename):
    pass


def upload_region_image(instance, filename):
    pass


def upload_item_image(instance, filename):
    pass


def upload_page_image(instance, filename):
    pass


class City(models.Model):
    """ Города Турции """

    name = models.CharField(u'Название', max_length=245)
    description = HTMLField(u'Описание', blank=True, null=True)
    image = AjaxImageField(u'Изображение', upload_to='catalog/city', blank=True, null=True)
    order = models.IntegerField(u'Порядок вывода', default=350)
    visible = models.BooleanField(u'Показывать', default = True)
    slug = models.SlugField(u'Слаг', max_length=255, null=True, unique=True, blank=True)

    # Метатеги
    meta_title = models.CharField(u'Мета заголовок', max_length=255, help_text=u'Метатег title', blank=True)
    meta_description = models.TextField(u'Мета описание', help_text=u'Метатег description', blank=True)
    meta_keywords = models.TextField(u'Ключевые слова ', help_text=u'Метатег keywords', blank=True)

    @models.permalink
    def get_absolute_url(self):
        return ('catalog-city', [self.slug])

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = generate_slug(self, self.slug or self.name)
        super(City, self).save(*args, **kwargs)

    def get_regions(self):
        return self.region_set.filter(visible=True)

    @classmethod
    def get_all_regions(cls):
        cities = cls.objects.filter(visible=True)
        result = [('', _(u'-- Выберите регион'))]
        for city in cities:
            result.append(
                (city.name, [(r.pk, r.name) for r in city.get_regions()])
            )
        return result

    class Meta:
        ordering = 'order', 'name'
        verbose_name = u'город'
        verbose_name_plural = u'Города'


class CityImage(models.Model):
    """Изображение в городе"""

    city = models.ForeignKey(City, verbose_name=u'город', null=True)
    image = AjaxImageField(u'Изображение', upload_to='catalog/cityimage', blank=True)
    title = models.CharField(u'Заголовок изображения', max_length=245, null=True, blank=True, default='')

    def __unicode__(self):
        return unicode(self.city) + ' :: ' + unicode(self.pk)

    class Meta:
        ordering = 'pk',
        verbose_name = u'изображение'
        verbose_name_plural = u'Изображения'


class Region(models.Model):
    """ Регион """

    name = models.CharField(u'Название', max_length=245)
    city = models.ForeignKey(City, verbose_name=u'Город')
    description = HTMLField(u'Описание', blank=True, null=True)
    order = models.IntegerField(u'Порядок вывода', default=350)
    slug = models.SlugField(u'Слаг', max_length=255, null=True, unique=True, blank=True)
    visible = models.BooleanField(u'Показывать', default = True)

    # Метатеги
    meta_title = models.CharField(u'Мета заголовок', max_length=255, help_text=u'Метатег title', blank=True)
    meta_description = models.TextField(u'Мета описание', help_text=u'Метатег description', blank=True)
    meta_keywords = models.TextField(u'Ключевые слова ', help_text=u'Метатег keywords', blank=True)

    @models.permalink
    def get_absolute_url(self):
        return ('catalog-objects-by-region', [self.slug])

    def __unicode__(self):
        return self.city.name + u'/' + self.name

    def save(self, *args, **kwargs):
        self.slug = generate_slug(self, self.slug or self.name)
        super(Region, self).save(*args, **kwargs)

    class Meta:
        ordering = 'order', 'city__name', 'name'
        verbose_name = u'Регион'
        verbose_name_plural = u'Регионы'


class RegionImage(models.Model):
    """ Изображение в городе """

    region = models.ForeignKey(Region, verbose_name=u'Район', null=True)
    image = AjaxImageField(u'Изображение', upload_to='catalog/region', blank=True)
    title = models.CharField(u'Заголовок изображения', max_length=245, null=True, blank=True, default='')

    def __unicode__(self):
        return unicode(self.region) + ' :: ' + unicode(self.pk)

    class Meta:
        ordering = 'pk',
        verbose_name = u'изображение'
        verbose_name_plural = u'Изображения'


class Type(models.Model):
    """ Типы недвижимости """
    
    name = models.CharField(u'Название', max_length=245)
    description = HTMLField(u'Описание', blank=True, null=True)
    order = models.IntegerField(u'Порядок вывода', default=350)
    visible = models.BooleanField(u'Показывать', default = True)
    slug = models.SlugField(u'Слаг', max_length=255, null=True, unique=True, blank=True)

    # Метатеги
    meta_title = models.CharField(u'Мета заголовок', max_length=255, help_text=u'Метатег title', blank=True)
    meta_description = models.TextField(u'Мета описание', help_text=u'Метатег description', blank=True)
    meta_keywords = models.TextField(u'Ключевые слова ', help_text=u'Метатег keywords', blank=True)

    def __unicode__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = generate_slug(self, self.slug or self.name)
        super(Type, self).save(*args, **kwargs)
        
    def is_sale_active(self):
        return Item.objects.filter(type=self, visible=True).exclude(deal='rent').count() > 0

    def is_rent_active(self):
        return Item.objects.filter(type=self, visible=True).exclude(deal='sale').count() > 0
        
    class Meta:
        ordering = 'order', 'name'
        verbose_name = u'тип'
        verbose_name_plural = u'Типы недвижимости'


class Item(models.Model):
    """ Объект недвижимости """
    
    DEAL_CHOICES = (  # Тип сделки
        (u'both', u'Продажа и аренда'),
        (u'sale', _(u'Продажа')),
        (u'rent', _(u'Аренда')),
    )
    
    RENT_TIME_CHOICES = (
        (u'month', _(u'месяц')),
        (u'week', _(u'неделю')),
        (u'day', _(u'сутки')),
    )

    SLEEPING_ROOM = (
        (u'studio', _(u'Студия')),
        (u'1', _(u'1')),
        (u'2', _(u'2')),
        (u'more2', _(u'Более 2')),
    )

    updated = models.DateTimeField(u'Обновленно', auto_now=True)
    codename = models.CharField(u'Код объекта', max_length=255, unique=True)
    
    deal = models.CharField(u'Тип сделки', choices=DEAL_CHOICES, default=u'sale', max_length=255)

    region = models.ForeignKey(Region, verbose_name=u'Регион', null=True)
    type = models.ForeignKey(Type, verbose_name=u'Тип объекта', null=True)
    title = models.CharField(u'Заголовок объекта', max_length=255)
    
    lat = models.CharField(u'Широта', max_length=255, blank=True, null=True)
    lng = models.CharField(u'Долгота', max_length=255, blank=True, null=True)
    
    short_description = models.TextField(u'Краткое описание', blank=True, null=True)
    description = HTMLField(u'Полное описание', blank=True, null=True)

    square_live = models.DecimalField(u'Жилая площадь', max_digits=10, decimal_places=2, help_text=u'Квадратных метров', default=0)
    square_all = models.DecimalField(u'Общая площадь', max_digits=10, decimal_places=2, help_text=u'Квадратных метров', default=0)
    square = models.DecimalField(u'Площадь земли', max_digits=10, decimal_places=2, help_text=u'Квадратных метров', default=0)

    sleeping_room = models.CharField(u'Количество спален', max_length=255, default=u'1', choices=SLEEPING_ROOM)
    bath_room = models.IntegerField(u'Количество ванн', default=0)
    
    price_sale = models.DecimalField(u'Цена продажи', max_digits=10, decimal_places=2, help_text=u'Цена задается в евро', default=0)
    price_sale_discount = models.DecimalField(u'Цена продажи со скидкой', max_digits=10, decimal_places=2, help_text=u'Цена задается в евро', default=0)
    price_rent = models.DecimalField(u'Цена аренды', max_digits=10, decimal_places=2, help_text=u'Цена задается в евро', default=0)
    price_rent_discount = models.DecimalField(u'Цена аренды со скидкой', max_digits=10, decimal_places=2, help_text=u'Цена задается в евро', default=0)
    
    rent_time = models.CharField(u'Цена аренды за', max_length=255, choices=RENT_TIME_CHOICES, default = u'month')
    
    image = AjaxImageField(u'Основное изображение', upload_to='catalog/item', blank=True, null=True)
    
    visible = models.BooleanField(u'Показывать', default=True)
    slug = models.SlugField(u'Слаг', max_length=255, null=True, unique=True, blank=True)

    is_new = models.BooleanField(u'Новинка', default=False)
    is_special = models.BooleanField(u'Спецпредложение', default=False)
    is_sold = models.BooleanField(u'Продано', default=False)

    view_count = models.IntegerField(u'Количество просмотров', default=0)

    # Метатеги
    meta_title = models.CharField(u'Мета заголовок', max_length=255, help_text=u'Метатег title', blank=True)
    meta_description = models.TextField(u'Мета описание', help_text=u'Метатег description', blank=True)
    meta_keywords = models.TextField(u'Ключевые слова ', help_text=u'Метатег keywords', blank=True)

    #данные владельца
    person = models.CharField(u'Персона', max_length=255, blank=True, null=True)
    mail = models.CharField(u'E-mail', max_length=255, blank=True, null=True)
    phone = models.CharField(u'Телефон', max_length=255, blank=True, null=True)


app/catalog/templates/catalog/_map.html
{% load xendor_tags %}
<!-- ymaps.geocode('{% get_setting 'Адрес для яндекс-карт' %}', { results: 1 }).then(function (res) { -->

<script type="text/javascript">
	function initialize() {
  		var latlang = new google.maps.LatLng({{item.lat}}, {{item.lng}});
  		
  		var mapOptions = {
	      center: latlang,
	      zoom: 13
	    };
	    
	    var map = new google.maps.Map(document.getElementById("map-canvas"),
	        mapOptions);  
	        
	     // var image = 'images/image.png';  //можно вместо красного пузырика сделать флажок или котенка
	     var marker = new google.maps.Marker({
		      position: latlang,
		      map: map,
		      title: ''
		      //icon: image
		  });
	};
	  
	google.maps.event.addDomListener(window, 'load', initialize);
</script>

<div class="lpanel" style="padding: 0;">
    <div id="map-canvas" style="height: 250px; width: 100%;"></div>	
</div>

app/catalog/templates/catalog/city-rent.html
{% extends 'catalog/index.html' %}
{% load xendor_tags catalog_tags i18n %}


{% block title %}
	<h1>{{ city }}. {% trans 'Аренда' %}.</h1>
{% endblock %}

{% block submenu %}
    <div class="lpanel submenu" style="padding: 10px;">

        <a href="{% url 'catalog-objects-by-city' city.slug %}" class="btn btn-primary" style="width: 100%;"> {% trans 'Все объекты' %} {% xicon 'arrow-right' %}</a>
        <div class="gap-10"></div>
        <a href="{% url 'catalog-sale-by-city' city.slug %}" class="special-link"> {% xicon 'star' %} {{ city }}. {% trans 'Продажа' %}.</a>
        <div class="gap-20"></div>

        <h2>{% trans 'Районы' %}</h2>
        <ul class="list-unstyled article-widget">
            {% for region in city.get_regions %}
                <li><a href="{{ region.get_absolute_url }}">{{ region.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="gap-20"></div>

{% endblock %}

app/catalog/templates/catalog/city.html
{% extends 'catalog/index.html' %}
{% load xendor_tags catalog_tags i18n %}


{% block title %}<h1>{{ object }}</h1>{% endblock %}

{% block center %}

    {% if object.image %}
    <img src="{{ object.image|xthumbnail:'250;150;fix' }}" alt="" style="float: left; padding-right: 20px;"/>
    {% endif %}
    {{ object.description|safe }}

    <a href="{% url 'catalog-objects-by-city' object.slug %}"
       class="btn btn-primary pull-right">{% trans 'Смотреть все объекты' %} "{{ object }}"</a>
    <br class="clear"/>
    <div class="gap-20"></div>

    <div class="lpanel " style="padding: 10px; padding-bottom: 0">
        <h2>{% trans 'Фотогалерея' %}</h2>

        <div class="row">
            {% for image in object.cityimage_set.all %}
                <div class="col-xs-6">
                    <a href="{{ image.image|xthumbnail:'1600;1200;fix' }}" rel="city-gallery" title="{{ image.title }}" class="fancybox">
                        <img src="{{ image.image|xthumbnail:'160;160;fix' }}" alt="" style="width: 100%;"/>
                    </a>
                    <div class="gap-20"></div>
                </div>
            {% endfor %}
        </div>

    </div>


{% endblock %}

{% block submenu %}
    <div class="lpanel submenu" style="padding: 10px;">
        <a href="{% url 'catalog-sale-by-city' object.slug %}" class="btn btn-primary" style="width: 100%;">
             {% trans 'Продажа' %} {% xicon 'arrow-right' %}
        </a>
        <div class="gap-10"></div>
        <a href="{% url 'catalog-rent-by-city' object.slug  %}" class="btn btn-primary" style="width: 100%;">
             {% trans 'Аренда' %} {% xicon 'arrow-right' %}
        </a>
        <div class="gap-20"></div>

        <h2>{% trans 'Районы' %}</h2>
        <ul class="list-unstyled article-widget">
            {% for region in object.get_regions %}
                <li><a href="{{ region.get_absolute_url }}">{{ region.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="gap-20"></div>

{% endblock %}

app/catalog/templates/catalog/index.html
{% extends 'home.html' %}
{% load catalog_tags xendor_tags i18n %}



{% block center %}
    {{ page.content|safe }}

	{% include 'catalog/include/list.html' %}
{% endblock %}

{% block right %}
    {% block submenu %}
        <div class="lpanel" style="padding: 10px;">
            <a href="{% url 'catalog-sale' %}" class="btn btn-primary" style="width: 100%;">
                 {% trans 'Продажа' %} {% xicon 'arrow-right' %}
            </a>
            <div class="gap-10"></div>
            <a href="{% url 'catalog-rent' %}" class="btn btn-primary" style="width: 100%;">
                 {% trans 'Аренда' %} {% xicon 'arrow-right' %}
            </a>
        </div>
        <div class="gap-20"></div>
    {% endblock %}

    {{ block.super }}
{% endblock %}

app/catalog/templates/catalog/post-object.html
{% extends 'base.html' %}
{% load xendor_tags bootstrap3 i18n %}

{% block content %}
    <div class="row">
        <div class="col-xs-24">
            <h1>{{ page.title }}</h1>

            {{ page.content|safe }}

            <form  action="{% url 'catalog-post-object' %}"  method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-xs-12">
                        <div class="lpanel" style="padding: 10px;">
                            <h2>{% trans 'Общая информация' %}</h2>
                            {{ form.errors }}

                            {% bootstrap_field form.description %}

                            {% bootstrap_field form.deal %}

                            {% bootstrap_field form.price %}

                            {% bootstrap_field form.square_live %}

                            {% bootstrap_field form.square_all %}
                            {% bootstrap_field form.square %}
                            {% bootstrap_field form.region %}
                            {% bootstrap_field form.type %}
                            {% bootstrap_field form.title %}
                            {% bootstrap_field form.sleeping_room %}
                            {% bootstrap_field form.bath_room %}

                        </div>

                        <div class="gap-20"></div>
                        <div class="lpanel" style="padding: 10px;">
                            <h2>{% trans 'Данные продавца' %}</h2>
                            {% bootstrap_field form.person %}
                            {% bootstrap_field form.mail %}
                            {% bootstrap_field form.phone %}
                            {% bootstrap_field form.captcha %}
                        </div>
                    </div>

                    <div class="col-xs-12 form-horizontal">
                        <div class="lpanel" style="padding: 10px;">
                            <h2>{% trans 'Характеристики объекта' %}</h2>

                            {% for tag_category in tag_categories %}
                            <h3 class="pull-right">{{ tag_category }}</h3>
                            <br class="clear"/>
                            {% for tag in tag_category.tag_set.all %}
                                <div class="form-group">
                                    <label class="col-xs-8 control-label">{{ tag.name }}</label>
                                    <div class="col-xs-16">
                                        <input type="text" class="form-control" name="tag_{{ tag.pk }}" placeholder="{% trans 'Введите свое значение' %}">
                                    </div>
                                </div>
                            {% endfor %}
                        {% endfor %}
                        </div>

                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-24">

                    </div>
                </div>
                <hr/>
                <input type="submit" class="btn btn-primary" value="{% trans 'Сохранить и перейти к добавлению изображений' %}">
            </form>
        </div>
    </div>

{% endblock %}

app/catalog/templates/catalog/print.html
{% extends 'base_print.html' %}
{% load xendor_tags catalog_tags %}

{% block subtitle %}
	<div class="gap-30"></div>
	<span class="pull-right label label-lg label-codename label-price" style="margin-top: -10px">ID: {{object.codename}}</span>
{% endblock %}

{% block title %}
<h1>
	{{ object }}
</h1>
<center>
	{% fragment 'телефон' %} | {% fragment 'ссылка на сайт' %}
</center>
{% endblock %}

{% block content %}
    {% with object as item %}
    <div class="row catalog">
        <div class="col-sm-6">
            <span class="thumbnail fancybox" rel="1">
                <img src="{{ item.image|xthumbnail:'1000;600;fix' }}" alt="" style="width: 100%"/>
            </span>
            <div class="text-center well well-sm" style="background: white; border-top: none;">
	            {% if not item.deal == 'rent' %}
		            <div class="money">
		            	{% if item.price_sale_discount %}
		            	   {% xicon 'euro' %}&nbsp;{{item.price_sale_discount|x1000}}
		            	   <strike>{{item.price_sale|x1000}}</strike>
		            	{% else %}
		            	   {% xicon 'euro' %}&nbsp;{{item.price_sale|x1000}}
		            	{% endif %}
		            </div>
	            {% endif %}
	            {% if not item.deal == 'sale' %}
		            <div class="money">
		            	{% xicon 'euro' %}
		            	{% if item.price_rent_discount %}
		            	   {{item.price_rent_discount|x1000}}
		            	   <strike>{{item.price_rent|x1000}}</strike>
		            	{% else %}
		            	   {{item.price_rent|x1000}}
		            	{% endif %}
		            	<span>
		            		{% if item.rent_time == 'month' %}/&nbsp;месяц{% else %}/&nbsp;неделя{% endif %}
		            	</span>
		            </div>
	            {% endif %}
            </div>
        </div>
        <div class="col-sm-18">
        	 <table width="100%" class="table table-striped table-hover table-bordered">
                <tr>
                    <th>Расположение:</th>
                    <td colspan="3">{{item.city}}</td>
                </tr>
                <tr>
                    <th>Тип недвижимости:</th>
                    <td>{{item.type}}</td>
                    <th>Комплекс:</th>
                    <td>
                    	{% if item.complex %}
                    		{{item.complex}}
                    	{% else %}
                    		–
                    	{% endif %}
                    </td>
                </tr>
                <tr>
                	<th>Количество спален/ванн:</th>
                    <td>{{item.sleeping_room}}/{{item.bath_room}}</td>
                    <th>Общая площадь:</th>
                    <td>
                    	{% if item.square_all %}
                    		{{item.square_all|x1000}} М<sup>2</sup>
                    	{% else %}
                    		–
                    	{% endif %}
                    </td>
                </tr>
                <tr>
                    <th>Площадь земли:</th>
                    <td>
                    	{% if item.square %}
                    		{{item.square|x1000}} М<sup>2</sup>
                    	{% else %}
                    		уточняйте
                    	{% endif %}
                    </td>
                    <th>Жилая площадь:</th>
                    <td>
                    	{% if item.square_live %}
                    		{{item.square_live|x1000}} М<sup>2</sup>
                    	{% else %}
                    		–
                    	{% endif %}
                    </td>
                </tr>
            	<tr>
            	{% for tag in item.objectproperty_set.all %}
            			<th>{{tag.tag.name}}</th>
            			<td>{{tag.value}}</td>
            		{% if forloop.counter|divisibleby:2 %}
            		</tr>
            		<tr>
            		{% endif %}
            	{% endfor %}
            	</tr>
            	<tr>
            		<th>
            			Обновленно
            		</th>
            		<td>
            			{{item.updated}}
            		</td>
            	</tr>
            </table>
        </div>
     </div>
     <div class="row">
        <div class="col-sm-6">
        </div>
        <div class="col-sm-18" style="padding-right: 50px">
        	<div class="gap-5"></div>
            {{object.description|safe}}
            <div class="gap-5"></div>
            <a href="mailto:{% get_setting 'E-mail администратора' %}" class="btn btn-success btn-sm">{% xicon 'envelope' %} Отправить запрос</a>
        </div>
    </div>
	{% if item.itemimage_set.all|length > 0 %}
	<div class="gap-20"></div>
	<div class="row">
		{% for image in item.itemimage_set.all %}
		    <div class="col-md-4 col-xs-8">
		    	<span class="thumbnail">
		    		<img src="{{image.image|xthumbnail:'500;500;fix'}}" alt="{{image.title}}"/>
		    	</span>
		    </div>
		    {% if forloop.counter|divisibleby:6 %}
		    	</div><div class="row">
		    {% endif %}
		{% endfor %}
	</div>
	{% endif %}
    
    {% endwith %}
{% endblock %}

{% block js %}
<script type="text/javascript" charset="utf-8">
	$(document).ready(function(){
		window.print();
		return true;
	});
</script>
{% endblock %}

app/catalog/templates/catalog/search.html
{% extends 'home.html' %}
{% load xendor_tags catalog_tags i18n %}

{% block title %}<h1 class="">{% trans 'Поиск объектов' %}</h1>{% endblock %}
{% block center %}

	{% include 'catalog/include/list.html' %}
{% endblock %}